/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mjpeg_live555_MjpegLive */

#ifndef _Included_com_example_mjpeg_live555_MjpegLive
#define _Included_com_example_mjpeg_live555_MjpegLive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mjpeg_live555_MjpegLive
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_mjpeg_1live555_MjpegLive_start
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
